baseURL = "http://mlrumble.github.io"
disqusShortname = "mlrumble"
googleAnalytics = "UA-110323565-1"
languageCode = "en-us"
pygmentsCodeFences = true
theme = "kiera"
title = "MLRumble"
[author]
facebook = ""
github = "mlrumble"
gitlab = ""
instagram = ""
linkedin = ""
name = "MLRumble"
twitter = "mlrumble"
[params]
description = "A Data Science Learning Resource to learn about AI, Deep Learning, NLP"
keywords = "python,data science,machine learning, analytics, big data, bigdata, maths, shell, bash, awk, hadoop, spark, statistics, data analysis, data science, classification, regression, vowpal wabbit, spearmint, random forest"
tagline = "Code is life"
