---
label: Default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
  config:
    required: true
- name: keywords
  label: Keywords
  type: list
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
  config:
    required: true
pages:
- content/posts/asda.md
